
name: Windows RDP on GitHub Actions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Maximize CPU performance
        run: |
          # The Runner is a VM, so it will already have high performance settings,
          # but this ensures no power throttling if it's a specific image.
          Write-Host "Setting power plan to high performance..."
          powercfg /setactive 8c5e9000-dc2f-487d-947f-8c0e25470008

      - name: Setup Ngrok
        uses: lokirf/github-actions-rdp@main
        with:
          ngrok_token: ${{ secrets.NGROK_AUTH_TOKEN }}
          ngrok_protocol: tcp
          ngrok_port: 3389
          # Default Windows RDP port is 3389
          # You can change the default RDP username/password here if you wish
          # rdp_user: asrejadid
          # rdp_password: 123456789

      - name: Connect to RDP
        run: echo "RDP is now running. Check the Logs for Ngrok connection details."

      - name: Keep job alive for 6 hours
        timeout-minutes: 360
        run: Start-Sleep -Seconds 21600 # Wait for 6 hours
